# Generated by Django 4.1.4 on 2023-01-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_de_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=200)),
                ('sobrenome_paciente', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=11)),
                ('primeiro_atendimento', models.DateField()),
                ('email', models.EmailField(max_length=200)),
                ('sexo_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=0, max_length=1)),
                ('foto', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompanhamento_medico', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('uso_medicacao', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('medicamento_em_uso', models.CharField(blank=True, max_length=200)),
                ('diabetico', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('hepatite', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('hiv', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('problemas_circulatorios', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('alergico', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('alergia_a', models.CharField(blank=True, max_length=100)),
                ('teve_cancer', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('tipo_cancer', models.CharField(blank=True, max_length=50)),
                ('gravidez', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('lactante', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('hipertensao', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('hipotensao', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default=1, max_length=3)),
                ('observacoes', models.TextField(blank=True, max_length=400)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_de_pacientes.cadastro_de_paciente')),
            ],
        ),
    ]
