# Generated by Django 4.1.5 on 2023-01-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_de_paciente',
            name='foto',
        ),
    ]
