# Generated by Django 4.1.5 on 2023-01-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_pacientes', '0002_remove_cadastro_de_paciente_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro_de_paciente',
            old_name='sexo_sexo',
            new_name='sexo',
        ),
        migrations.AlterField(
            model_name='cadastro_de_paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
