# Generated by Django 4.1.5 on 2023-01-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_pacientes', '0003_rename_sexo_sexo_cadastro_de_paciente_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='acompanhamento_medico',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='alergico',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='diabetico',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='gravidez',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hepatite',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hipertensao',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hipotensao',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='hiv',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='lactante',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='cadastro_de_pacientes.cadastro_de_paciente'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='problemas_circulatorios',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='teve_cancer',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='uso_medicacao',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=3),
        ),
    ]
