# Generated by Django 4.1.5 on 2023-01-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_pacientes', '0005_alter_anamnese_acompanhamento_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_de_paciente',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cadastro_de_paciente',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
    ]
