# Generated by Django 4.1.5 on 2024-01-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_pacientes', '0007_alter_anamnese_acompanhamento_medico_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro_de_paciente',
            new_name='CadastroDePaciente',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='alergia_a',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='problemas_circulatorios',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='tipo_cancer',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='uso_medicacao',
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='acompanhamento_medico',
            field=models.CharField(blank=True, default='Não faz', max_length=100),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='alergico',
            field=models.CharField(default='Nenhuma', max_length=50),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='diabetico',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='Não', max_length=50),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='medicamento_em_uso',
            field=models.CharField(blank=True, default='Não faz', max_length=200),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='teve_cancer',
            field=models.CharField(default='Não', max_length=50),
        ),
    ]
