# Generated by Django 4.1.5 on 2024-01-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_pacientes', '0008_rename_cadastro_de_paciente_cadastrodepaciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='cadastro_de_pacientes.cadastrodepaciente'),
        ),
    ]
