# Generated by Django 4.1.5 on 2023-03-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='fotos_procedimento')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
