# Generated by Django 4.1.4 on 2023-01-27 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar_venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('paciente', models.CharField(max_length=120)),
                ('servico', models.CharField(max_length=200)),
                ('produto', models.CharField(max_length=120)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.CharField(choices=[('cred', 'Crédito'), ('deb', 'Débito'), ('pix', 'Pix'), ('din', 'Dinheiro')], max_length=4)),
            ],
        ),
    ]
