# Generated by Django 4.1.5 on 2023-01-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrar_venda',
            old_name='produto',
            new_name='produtos',
        ),
        migrations.AlterField(
            model_name='registrar_venda',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrar_venda',
            name='pagamento',
            field=models.CharField(choices=[('cred', 'Crédito'), ('deb', 'Débito'), ('pix', 'Pix'), ('din', 'Dinheiro')], default=2, max_length=4),
        ),
    ]
