# Generated by Django 4.1.5 on 2023-01-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_rename_produto_registrar_venda_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_venda',
            name='pagamento',
            field=models.CharField(max_length=4),
        ),
    ]
