# Generated by Django 4.1.5 on 2023-01-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_registrar_venda_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar_despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('produtos', models.CharField(max_length=300)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.CharField(max_length=4)),
                ('observacoes', models.CharField(max_length=300)),
            ],
        ),
    ]
