# Generated by Django 4.1.5 on 2024-01-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_registrar_despesa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrar_despesa',
            new_name='RegistrarDespesa',
        ),
        migrations.RenameModel(
            old_name='Registrar_venda',
            new_name='RegistrarVenda',
        ),
    ]
